### ISSUE TITLE
MPV forcefully takes focus when a new episode is played

### ISSUE THREAD

**Issue by MrSegi** [jellyfin/jellyfin-mpv-shim#218]
**Describe the bug**
When playing any episodes in sequence MPV takes focus on next episode start. This will even minimize applications that are fullscreened.

**To Reproduce**
1. Have MPV playing on your second monitor.
2. Do something on your primary monitor.
3. MPV switches to next episode and MPV is now accepting keyboard and mouse input.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by iwalton3** [comment]
This was done because MPV has a nasty habit of opening behind other windows when you cast to it. It could probably help to make this configurable or only do it once per playback session.

In the mean time if you change the window title to not end with " - mpv" it'll disable this. (https://github.com/mpv-player/mpv/issues/2188#issuecomment-127096262)
